import pino from 'pino'
import { env } from './env.js'

export const logRedactPaths = [
  'req.headers.authorization',
  'req.headers.cookie',
  'req.body.password',
  'req.body.currentPassword',
  'req.body.newPassword',
  'req.body.token',
  'req.body.refreshToken',
  'req.body.firstName',
  'req.body.lastName',
  'req.body.dateOfBirth',
  'req.body.phone',
  'req.body.email',
  'req.body.addressText',
  'req.body.emergencyContactName',
  'req.body.emergencyContactPhone',
  'req.body.diagnoses',
  'req.body.treatments',
  'req.body.reports',
  'req.body.items',
  'req.body.diagnosisText',
  'req.body.treatmentText',
  'req.body.reportText',
  'req.body.dosage',
  'req.body.instructions',
  'req.body.frequency',
  'req.body.duration',
  'req.body.clinicalNote',
  'req.body.resultValue',
  'req.body.resultNote',
  'req.body.referenceRangeSnapshot',
  '*.diagnosisText',
  '*.treatmentText',
  '*.reportText',
  '*.dosage',
  '*.instructions',
  '*.clinicalNote',
  '*.resultValue',
  '*.resultNote',
  '*.referenceRangeSnapshot',
  '*.clinical_note',
  '*.result_value',
  '*.result_note',
  '*.reference_range_snapshot',
  'password',
  'currentPassword',
  'newPassword',
  'passwordHash',
  'token',
  'tokenHash',
  'accessToken',
  'refreshToken',
  '*.password',
  '*.currentPassword',
  '*.newPassword',
  '*.passwordHash',
  '*.token',
  '*.tokenHash',
  '*.accessToken',
  '*.refreshToken',
] as const

export const logger = pino({
  level: env.logging.level,
  base: {
    service: 'hms-api',
    environment: env.nodeEnv,
  },
  redact: {
    paths: [...logRedactPaths],
    censor: '[REDACTED]',
  },
})
