import pino from 'pino'
import { env } from './env.js'

export const logger = pino({
  level: env.logging.level,
  base: {
    service: 'hms-api',
    environment: env.nodeEnv,
  },
  redact: {
    paths: [
      'req.headers.authorization',
      'req.headers.cookie',
      'req.body.password',
      'req.body.currentPassword',
      'req.body.newPassword',
      'req.body.token',
      'req.body.refreshToken',
      'req.body.firstName',
      'req.body.lastName',
      'req.body.dateOfBirth',
      'req.body.phone',
      'req.body.email',
      'req.body.addressText',
      'req.body.emergencyContactName',
      'req.body.emergencyContactPhone',
      'req.body.diagnoses',
      'req.body.treatments',
      'req.body.reports',
      'req.body.items',
      'req.body.diagnosisText',
      'req.body.treatmentText',
      'req.body.reportText',
      'req.body.dosage',
      'req.body.instructions',
      'req.body.frequency',
      'req.body.duration',
      '*.diagnosisText',
      '*.treatmentText',
      '*.reportText',
      '*.dosage',
      '*.instructions',
      'password',
      'currentPassword',
      'newPassword',
      'passwordHash',
      'token',
      'tokenHash',
      'accessToken',
      'refreshToken',
      '*.password',
      '*.currentPassword',
      '*.newPassword',
      '*.passwordHash',
      '*.token',
      '*.tokenHash',
      '*.accessToken',
      '*.refreshToken',
    ],
    censor: '[REDACTED]',
  },
})
