export const ACCESS_TOKEN_TTL_SECONDS = 15 * 60
export const REFRESH_ABSOLUTE_TTL_MS = 7 * 24 * 60 * 60 * 1000
export const REFRESH_IDLE_TTL_MS = 30 * 60 * 1000
export const TEMPORARY_LOCK_MS = 15 * 60 * 1000
export const FAILED_LOGIN_LIMIT = 5
export const LOGIN_TRANSACTION_TIMEOUT_MS = 20_000

export const AUTH_CSRF_HEADER = 'x-hms-csrf'
export const AUTH_CSRF_VALUE = '1'
export const REFRESH_COOKIE_PATH = '/api/v1/auth'

export const PERMISSIONS = {
  identitySelfRead: 'identity.self.read',
  identityPasswordChange: 'identity.password.change',
  patientRead: 'patient.read',
  patientCreate: 'patient.create',
  patientUpdate: 'patient.update',
  departmentRead: 'department.read',
  departmentCreate: 'department.create',
  departmentUpdate: 'department.update',
  employeeRead: 'employee.read',
  employeeCreate: 'employee.create',
  employeeUpdate: 'employee.update',
  doctorRead: 'doctor.read',
  doctorCreate: 'doctor.create',
  doctorUpdate: 'doctor.update',
  doctorScheduleRead: 'doctor_schedule.read',
  doctorScheduleCreate: 'doctor_schedule.create',
  doctorScheduleUpdate: 'doctor_schedule.update',
  appointmentRead: 'appointment.read',
  appointmentCreate: 'appointment.create',
  appointmentUpdate: 'appointment.update',
  appointmentCancel: 'appointment.cancel',
  appointmentReschedule: 'appointment.reschedule',
  appointmentStatusUpdate: 'appointment.status.update',
  medicalRecordRead: 'medical_record.read',
  medicalRecordCreate: 'medical_record.create',
  medicalRecordUpdate: 'medical_record.update',
  medicalRecordFinalize: 'medical_record.finalize',
  medicalRecordAmend: 'medical_record.amend',
  prescriptionRead: 'prescription.read',
  prescriptionCreate: 'prescription.create',
  prescriptionCancel: 'prescription.cancel',
  medicineRead: 'medicine.read',
  medicineCreate: 'medicine.create',
  medicineUpdate: 'medicine.update',
  medicineDeactivate: 'medicine.deactivate',
  medicineReactivate: 'medicine.reactivate',
  inventoryRead: 'inventory.read',
  stockReceive: 'stock.receive',
  stockAdjust: 'stock.adjust',
  stockMovementRead: 'stock.movement.read',
  prescriptionDispense: 'prescription.dispense',
  prescriptionReverse: 'prescription.reverse',
  labTestRead: 'lab_test.read',
  labRequestRead: 'lab_request.read',
  labRequestCreate: 'lab_request.create',
  labSampleCollect: 'lab_sample.collect',
  labResultEnter: 'lab_result.enter',
  invoiceRead: 'invoice.read',
  invoiceCreate: 'invoice.create',
  invoiceUpdate: 'invoice.update',
  invoiceIssue: 'invoice.issue',
  invoiceVoid: 'invoice.void',
  paymentRead: 'payment.read',
  paymentCreate: 'payment.create',
  paymentReverse: 'payment.reverse',
  admissionRead: 'admission.read',
  admissionCreate: 'admission.create',
  admissionUpdate: 'admission.update',
  admissionDischarge: 'admission.discharge',
  admissionCancel: 'admission.cancel',
  reportPatientRead: 'report.patient.read',
  reportAppointmentRead: 'report.appointment.read',
  reportRevenueRead: 'report.revenue.read',
  reportPharmacyRead: 'report.pharmacy.read',
  reportLaboratoryRead: 'report.laboratory.read',
  reportStaffRead: 'report.staff.read',
  attendanceRead: 'attendance.read',
  attendanceCreate: 'attendance.create',
  attendanceUpdate: 'attendance.update',
  leaveRead: 'leave.read',
  leaveCreate: 'leave.create',
  leaveUpdate: 'leave.update',
  leaveApprove: 'leave.approve',
  leaveCancel: 'leave.cancel',
  patientDocumentRead: 'patient_document.read',
  patientDocumentCreate: 'patient_document.create',
  patientDocumentUpdate: 'patient_document.update',
  patientDocumentDelete: 'patient_document.delete',
  userRead: 'user.read',
  userCreate: 'user.create',
  userUpdate: 'user.update',
  userDeactivate: 'user.deactivate',
  userRoleUpdate: 'user.role.update',
  userPasswordReset: 'user.password.reset',
  auditRead: 'audit.read',
} as const
